packages:
  - apps/*
  - packages/*

catalogs:
  default:
    "@astrojs/check": ^0.9.8
    "@biomejs/biome": ^2.4.8
    "@types/node": ^25.5.0
    astro: ^6.0.8
    turbo: ^2.9.6
    typescript: ^6.0.3
    vitest: ^4.0.15
